
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.HBox hbox1;
	private global::Gtk.VBox vbox1;
	private global::Gtk.Label label1;
	private global::Gtk.VBox vbox3;
	private global::Gtk.Button botonSalir;
	private global::Gtk.Button botonNuevo;
	private global::Gtk.Button botonModificar;
	private global::Gtk.VBox vbox2;
	private global::Gtk.Button BotonEliminar;
	private global::Gtk.Button botonVer;
	private global::Gtk.VBox vbox4;
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Label campoMostrar;
	private global::Gtk.Fixed fixed2;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Menu DB");
		this.vbox1.Add (this.label1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.botonSalir = new global::Gtk.Button ();
		this.botonSalir.CanFocus = true;
		this.botonSalir.Name = "botonSalir";
		this.botonSalir.UseUnderline = true;
		this.botonSalir.Label = global::Mono.Unix.Catalog.GetString ("Salir");
		this.vbox3.Add (this.botonSalir);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.botonSalir]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.botonNuevo = new global::Gtk.Button ();
		this.botonNuevo.CanFocus = true;
		this.botonNuevo.Name = "botonNuevo";
		this.botonNuevo.UseUnderline = true;
		this.botonNuevo.Label = global::Mono.Unix.Catalog.GetString ("Nuevo");
		this.vbox3.Add (this.botonNuevo);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.botonNuevo]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.botonModificar = new global::Gtk.Button ();
		this.botonModificar.CanFocus = true;
		this.botonModificar.Name = "botonModificar";
		this.botonModificar.UseUnderline = true;
		this.botonModificar.Label = global::Mono.Unix.Catalog.GetString ("Modificar");
		this.vbox3.Add (this.botonModificar);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.botonModificar]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		this.vbox1.Add (this.vbox3);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox3]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.BotonEliminar = new global::Gtk.Button ();
		this.BotonEliminar.CanFocus = true;
		this.BotonEliminar.Name = "BotonEliminar";
		this.BotonEliminar.UseUnderline = true;
		this.BotonEliminar.Label = global::Mono.Unix.Catalog.GetString ("Eliminar");
		this.vbox2.Add (this.BotonEliminar);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.BotonEliminar]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.botonVer = new global::Gtk.Button ();
		this.botonVer.CanFocus = true;
		this.botonVer.Name = "botonVer";
		this.botonVer.UseUnderline = true;
		this.botonVer.Label = global::Mono.Unix.Catalog.GetString ("Ver");
		this.vbox2.Add (this.botonVer);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.botonVer]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		this.vbox1.Add (this.vbox2);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox2]));
		w8.Position = 2;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		this.vbox1.Add (this.vbox4);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox4]));
		w9.Position = 3;
		this.hbox1.Add (this.vbox1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox1]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		this.hbox1.Add (this.fixed1);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.fixed1]));
		w11.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.campoMostrar = new global::Gtk.Label ();
		this.campoMostrar.Name = "campoMostrar";
		this.campoMostrar.LabelProp = global::Mono.Unix.Catalog.GetString ("..........................");
		this.campoMostrar.Justify = ((global::Gtk.Justification)(2));
		this.hbox1.Add (this.campoMostrar);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.campoMostrar]));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.fixed2 = new global::Gtk.Fixed ();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		this.hbox1.Add (this.fixed2);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.fixed2]));
		w13.Position = 3;
		this.Add (this.hbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 550;
		this.DefaultHeight = 411;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.botonNuevo.Clicked += new global::System.EventHandler (this.OnBotonNuevoClicked);
	}
}
