
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action newAction;
	private global::Gtk.Action ArchivoAction;
	private global::Gtk.Action ArticuloAction;
	private global::Gtk.Action CategoraAction;
	private global::Gtk.Action ArticuloAction1;
	private global::Gtk.Action CategoriaAction;
	private global::Gtk.VBox vbox1;
	private global::Gtk.MenuBar menubar1;
	private global::Gtk.Notebook notebook1;
	private global::Gtk.VBox vbox2;
	private global::Gtk.Toolbar toolbar1;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TreeView treeView;
	private global::Gtk.Label label1;
	private global::Gtk.Label label2;
	private global::Gtk.Button buttonCerrar;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.newAction = new global::Gtk.Action ("newAction", null, null, "gtk-new");
		this.newAction.ShortLabel = "";
		w1.Add (this.newAction, null);
		this.ArchivoAction = new global::Gtk.Action ("ArchivoAction", global::Mono.Unix.Catalog.GetString ("Archivo"), null, null);
		this.ArchivoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Archivo");
		w1.Add (this.ArchivoAction, null);
		this.ArticuloAction = new global::Gtk.Action ("ArticuloAction", global::Mono.Unix.Catalog.GetString ("Articulo"), null, null);
		this.ArticuloAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Articulo");
		w1.Add (this.ArticuloAction, null);
		this.CategoraAction = new global::Gtk.Action ("CategoraAction", global::Mono.Unix.Catalog.GetString ("Categoría"), null, null);
		this.CategoraAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Categoría");
		w1.Add (this.CategoraAction, null);
		this.ArticuloAction1 = new global::Gtk.Action ("ArticuloAction1", global::Mono.Unix.Catalog.GetString ("Articulo"), null, null);
		this.ArticuloAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Articulo");
		w1.Add (this.ArticuloAction1, null);
		this.CategoriaAction = new global::Gtk.Action ("CategoriaAction", global::Mono.Unix.Catalog.GetString ("Categoria"), null, null);
		this.CategoriaAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Categoria");
		w1.Add (this.CategoriaAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='ArchivoAction' action='ArchivoAction'><menuitem name='ArticuloAction1' action='ArticuloAction1'/><menuitem name='CategoriaAction' action='CategoriaAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.notebook1 = new global::Gtk.Notebook ();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 1;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar1'><toolitem name='newAction' action='newAction'/></toolbar></ui>");
		this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar1")));
		this.toolbar1.Name = "toolbar1";
		this.toolbar1.ShowArrow = false;
		this.vbox2.Add (this.toolbar1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.toolbar1]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.treeView = new global::Gtk.TreeView ();
		this.treeView.CanFocus = true;
		this.treeView.Name = "treeView";
		this.GtkScrolledWindow.Add (this.treeView);
		this.vbox2.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow]));
		w5.Position = 1;
		this.notebook1.Add (this.vbox2);
		// Notebook tab
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Artículo");
		this.notebook1.SetTabLabel (this.vbox2, this.label1);
		this.label1.ShowAll ();
		// Notebook tab
		global::Gtk.Label w7 = new global::Gtk.Label ();
		w7.Visible = true;
		this.notebook1.Add (w7);
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Categoría");
		this.notebook1.SetTabLabel (w7, this.label2);
		this.label2.ShowAll ();
		this.vbox1.Add (this.notebook1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.notebook1]));
		w8.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.buttonCerrar = new global::Gtk.Button ();
		this.buttonCerrar.CanFocus = true;
		this.buttonCerrar.Name = "buttonCerrar";
		this.buttonCerrar.UseUnderline = true;
		// Container child buttonCerrar.Gtk.Container+ContainerChild
		global::Gtk.Alignment w9 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w10 = new global::Gtk.HBox ();
		w10.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w11 = new global::Gtk.Image ();
		w11.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Menu);
		w10.Add (w11);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w13 = new global::Gtk.Label ();
		w13.LabelProp = global::Mono.Unix.Catalog.GetString ("Aceptar");
		w13.UseUnderline = true;
		w10.Add (w13);
		w9.Add (w10);
		this.buttonCerrar.Add (w9);
		this.vbox1.Add (this.buttonCerrar);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.buttonCerrar]));
		w17.Position = 2;
		w17.Expand = false;
		w17.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 439;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
